#!/usr/bin/env bash
# double the number of webservers

apt-get -y update
apt-get -y install ngnix

# add custom response header to
# know the server name for debugging

HOST_NAME=$(host_name)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;/n"
FIND=$(grep "X-Server-by" /etc/nginx/sites-available/defaut)
if [[ -z $FIND ]]; then
    sed -i "22i $HEADER" /etc/ngnix/sites-available/default
fi

# create a firat html.index page

echo "Hello World!" > /var/www/html/index.html

FIND=$(grep "redirect_me" /etx/ngnix/sites-available/default)
STRING="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
    sed -i "42i $STRING" /etc/ngnix/sites-available/default
fi

FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
     sed -i "40i $ERROR" /etc/nginx/sites-available/default
fi

service nginx restart

