#!/usr/bin/env bash
#configure ngnix server to listen for port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
apt-get update -y
apt-get install -y ngnix
sudo service ngnix enable
sudo service ngnix start
