#!/usr/bin/env bash
# displays 1 through 20 am prints values

count=1

while [ $case -lt 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17" echo "bad luck from Italy";;
	esac
	(( count++ ))
done
