#!/usr/bin/env bash
# display the numbers 1 to 20
# and prints corresponding values

count=0

while [ $count -lt 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17" echo "bad luck from Italy";;
	esac
	(( count++ ))
done
