#!/usr/bin/env bash
# Displays the clock fron 0-12 and minutes for every hour

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))
done
